import {
  JetBrains_Mono,
  Poppins,
  Red_Hat_Display,
  Comfortaa,
  Chakra_Petch,
  Josefin_Sans,
  Sansita,
} from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import PageTransition from '@/components/PageTransition';
import StairTransition from '@/components/StairTransition';
import Footer from '@/components/Footer';
import FlareCursor from '@/components/FlareCursor';

const jetBrainsMono = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-jetbrainsMono',
});

// SEO Optimization
export const metadata = {
  title: 'capellax.',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={jetBrainsMono.variable}>
        <Header />
        {/* <FlareCursor /> */}
        <StairTransition />

        <PageTransition>{children}</PageTransition>
        <Footer />
      </body>
    </html>
  );
}
